version: '3'
services:
  mysql:
    image: mysql:5.6.27
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  
    container_name: mysqldb_1
    environment:
      MYSQL_ROOT_PASSWORD: passx123
      TZ: America/Mexico_City

volumes:
  mysqldata:
    driver: local